### ISSUE TITLE
Security of running node as root

### ISSUE THREAD

**Issue by jadudm** [scripting/pagePark#1]
Dear Dave,

I would encourage you to take a quick look at this post:

http://syskall.com/dont-run-node-dot-js-as-root/

Running node as root ("sudo") is probably a serious security hole, especially with a quick-and-dirty webserver. However, it looks like you could either a) within your code or b) from without give yourself the ability to run on port 80 without allowing anyone who hacks your server to gain instant root privs.

http://technosophos.com/2012/12/17/run-nodejs-apps-low-ports-without-running-root.html

https://www.digitalocean.com/community/tutorials/how-to-use-pm2-to-setup-a-node-js-production-environment-on-an-ubuntu-vps

http://syskall.com/dont-run-node-dot-js-as-root/

Your mileage may vary, but it feels like running servers as root is an insecure solution.

**Comment by scripting** [comment]
Thanks for the tip, I just tried your suggestion, and am running pagepark on port 80 without doing it as root. I'll post a link to the mail list.
