### ISSUE TITLE
Default markdown template missing

### ISSUE THREAD

**Issue by andrewshell** [scripting/pagePark#14]
It points to http://scripting.com/code/pagepark/defaultmarkdowntemplate.txt which is currently returning a 404.

**Comment by scripting** [comment]
OK -- I'm going to fix the default in the distribution, but in the meantime, you can fix it locally by adding this line to the top-level config.json.

` "urlDefaultMarkdownTemplate": "http://scripting.com/code/pagepark/templates/markdown/template.txt",`

**Comment by scripting** [comment]
Also I made the change on my primary PP server and it;'s fixed there.

http://lucky.wtf/test.md

Thanks for uncovering this, as you can tell I don't do a lot of Markdown. ;-)

**Comment by andrewshell** [comment]
Looks good!
