### ISSUE TITLE
Rendering opml files from Little Outliner

### ISSUE THREAD

**Issue by andrewshell** [scripting/pagePark#15]
I'm using pagePark installed at http://shll.me/

I took a stab at a few ways that I thought using little outliner opml files could work based on what I read in the docs.

My `index.opml` file currently looks like this:

```xml
<opml version="2.0">
    <head>
        <title>Shll.me</title>
        </head>
    <body>
        <outline text="homestead - include" type="include" url="http://storage2.littleoutliner.com/users/andrewshell/myOutlines/homestead.opml"/>
        <outline text="homestead - mirror" type="link" url="mirror.opml"/>
        </body>
    </opml>
```

And `config.json`:

```json
{
    "mirrors": {
        "/mirror.opml": "http://storage2.littleoutliner.com/users/andrewshell/myOutlines/homestead.opml"
    }
}
```

I would expect the first one to be rendered inline as if I had copied and pasted the body into the parent outline, but it seems to ignore the include and just renders the text. 

The second one I thought would link (which it does) to a rendered opml page, but it just shows the xml as plain text.

**Comment by scripting** [comment]
I think I can guess what you're trying to do but you don't say. 

Here's the guess -- you want to edit an outline using LO2 and have it appear, rendered, on http://shll.me/.

I'll start from there and see what I can come up with, and write up the result here.

**Comment by scripting** [comment]
Andrew, I did a little looking around -- a few comments.

1. mirrors is not the feature for this application. Its purpose is to provide for wholesale remapping of URLs. I added it for the XML-RPC website, which needed a lot of redirects. 

2. includes are not implemented in PagePark as you found.

3. There are ways to get site contents from S3 and go through the rendering process, but not from an arbitrary URL as far as I can see. 

4. I think there is a much easier [approach](http://my.this.how/davewiner/howtos.opml) for trying out using LO2 for FAQ-style docs. Go with that, and if that was the only reason for operating a PP server at this time you can put this project to rest. Your URLs will be on my.this.how, not your own domain, but we can deal with that later. 

I totally encourage you to use this. The problem has been that no one has been willing to go down this road with me, so I have no one to develop with. You;'ll see that all around the world I've created. Yes, it's sad, but I am willing to work with you, but it'll take time to smooth everything out.

**Comment by scripting** [comment]
Here's another link -- 

http://my.this.how/davewiner/howtosInLittleOutliner.opml

That's an example of a howto written with LO2. 

As you can see I updated it this morning, so it all appears to be working.

**Comment by andrewshell** [comment]
Here is my notes outline: http://my.this.how/andrewshell/notes.opml

**Comment by scripting** [comment]
difference between my stuff and their stuff -- mine is actual software you
can use. they come up with ideas that were out there decades ago and then
people cite them as if they're their original ideas. they also use trolling
and flaming as tools of coercion. ugh.
