### ISSUE TITLE
RFC: config.flServeConfigJson

### ISSUE THREAD

**Issue by scripting** [scripting/pagePark#24]
config.flServeConfigJson -- a new config value -- defaults false. 

1. Determines whether we serve config.json from each domain folder that has one. 

2. As a demo, here's an [example](http://defaultextensiondemo.userland.com/config.json) of a config.json file accessible over the web.

2. This was an oversight. I want to close this door asap, but in case people have an application for it, I want to make it possible to open door in a single case or globally. That's what config.flServeConfigJson is for.

3. if config.flServeConfigJson is false, we will return 404 not found for config.json files in domain folders. If it's true, we'll serve it just like any other file.

I wanted to ask existing PagePark users if they ever rely on remote access to config.json from one of their domains.

I don't imagine there are any, but who knows.

I'm not going to leave this door unclosed for long, but wanted to offer a brief period for comment.

**Comment by andrewshell** [comment]
I don’t access the file remotely so I think it’s good to close that door.

**Comment by gwthompson** [comment]
I don’t access the file remotely either so I’m fine with closing the door.

**Comment by mistersugar** [comment]
I don't access the file remotely either. I am ok with closing the door.

**Comment by gwthompson** [comment]
@scripting where’s the best place to ask questions about pagePark? Here? Twitter? Or ???

**Comment by scripting** [comment]
@gwthompson -- ask questions here that way other people can answer. i'm pretty overloaded.

**Comment by scripting** [comment]
v0.8.23 is out with this fix and fixes to the docs for persistent apps and the command line too.

https://github.com/scripting/pagePark#v0823-72821-by-dw

**Comment by gwthompson** [comment]
Sounds good! What’s the proper way to use the opml template in my domain folder as well as the code.js? Is this configurable without changing the url in the pagePark.js file itself?

**Comment by scripting** [comment]
@gwthompson -- sorry i meant to start a new issue here, not tack it on to this one.

and i'm sorry again i can't parse your question. you have to lay it out more clearly. i can't tell what you want to do, and what you've tried, and what docs you've already looked at.

**Comment by scripting** [comment]
Also @gwthompson — it’s good to say upfront what you’re trying to do. A lot of times people ask about details when there’s a simple way to do what they want to do.
