### ISSUE TITLE
Installing pagePark generates warnings. Run the fix?

### ISSUE THREAD

**Issue by sbwaters** [scripting/pagePark#26]
Hi, should I run npm audit fix as suggested and is that enough?

Thank you!

[BTW, the npm install requires a directory change to where package.json is located. I didn’t know that. Might be worth adding that to the "How to" instructions at 1.A.]

[sbwMacbookPro:~] sbw% cd /Applications/Utilities/pagePark-master 
[sbwMacbookPro:/Applications/Utilities/pagePark-master] sbw% npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
added 305 packages, and audited 306 packages in 18s
3 packages are looking for funding
  run `npm fund` for details
9 vulnerabilities (5 moderate, 4 high)
To address all issues, run:
  npm audit fix

Run `npm audit` for details.
[sbwMacbookPro:/Applications/Utilities/pagePark-master] sbw% npm audit
# npm audit report

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix`
node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/chokidar
    forever-monitor  >=1.6.0
    Depends on vulnerable versions of chokidar
    node_modules/forever-monitor
      forever  >=0.10.11
      Depends on vulnerable versions of flatiron
      Depends on vulnerable versions of forever-monitor
      node_modules/forever

minimist  <0.2.1
Severity: moderate
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
fix available via `npm audit fix`
node_modules/optimist/node_modules/minimist
  optimist  >=0.6.0
  Depends on vulnerable versions of minimist
  node_modules/optimist
    flatiron  >=0.3.9
    Depends on vulnerable versions of optimist
    node_modules/flatiron
      forever  >=0.10.11
      Depends on vulnerable versions of flatiron
      Depends on vulnerable versions of forever-monitor
      node_modules/forever
    nconf  0.6.9 - 0.7.1
    Depends on vulnerable versions of optimist
    node_modules/nconf
      broadway  0.2.9 - 0.3.6
      Depends on vulnerable versions of nconf
      node_modules/broadway

9 vulnerabilities (5 moderate, 4 high)

To address all issues, run:
  npm audit fix
[sbwMacbookPro:/Applications/Utilities/pagePark-master] sbw%

**Comment by scripting** [comment]
I can't afford the time it would take to figure out what each of them represents if anything.

**Comment by sbwaters** [comment]
Hmm. Maybe I had a point back then. Seen elsewhere recently:

"I learned a few things...

    I made a mistake in the instructions, I didn't tell the user how to install Node. I just told them to run npm install as if everyone has it installed. One of our best users got stuck there."

**Comment by scripting** [comment]
They're completely separate things. If you're trying to win an argument you're misusing this support forum.

**Comment by sbwaters** [comment]
Yes they are separate but similar. No argument intended. — I apologize if there is a better forum you can point to to help bootstrap Drummer users.

You are much more knowledgeable than many and your instructions assume more expertise than many have or can easily acquire. The instructions are not wrong, but they assume others are equally experienced or have similar configurations and software versions. 

You are occupied elsewhere, and should be … that being the best use of time.
It would be useful if others with your level of expertise could expand on the instructions to avoid some pitfalls. You are on your way to a very useful product if other power users can help bridge the knowledge gap.
