### ISSUE TITLE
How to kill the pagePark process in Ubuntu?

### ISSUE THREAD

**Issue by sbwaters** [scripting/pagePark#30]
How does one stop the pagePark process in Ubuntu? It was started by "node pagepark.js".

I tried:
     ps aux | grep node
to get the PID and then 
     kill -15 PID 
 and, when that didn’t work:
     kill -9 PID
Thank you.

**Comment by scripting** [comment]
https://www.google.com/search?q=how+do+you+kill+a+node+app+from+the+command+line&rlz=1C5CHFA_enUS743US747&oq=how+do+you+kill+a+node+app+from+the+command+line&aqs=chrome..69i57j33i299.7928j0j4&sourceid=chrome&ie=UTF-8

**Comment by scripting** [comment]
https://www.google.com/search?q=how+do+you+kill+a+node+app+from+the+command+line

**Comment by sbwaters** [comment]
When tried, it appears to restart. New PID. Console:
sbwaters@viewfromafar:/$ ps aux | grep node
sbwaters 1495352  0.8  6.5 642460 65284 ?        Ssl  03:23   0:01 node /pagePark/pagepark.js
sbwaters 1495400  0.0  0.0   8160   652 pts/1    S+   03:25   0:00 grep --color=auto node
sbwaters@viewfromafar:/$ kill -9 1495352
sbwaters@viewfromafar:/$ ps aux | grep node
sbwaters 1495401 20.2  7.1 643004 71692 ?        Ssl  03:26   0:01 node /pagePark/pagepark.js
sbwaters 1495419  0.0  0.0   8160   716 pts/1    S+   03:26   0:00 grep --color=auto node

**Comment by sbwaters** [comment]
The problem may be pp:

root@viewfromafar:/pagePark/cli# pp list

pageParkCommandLine v0.4.3, config == {
    "domain": "localhost",
    "port": 1349,
    "myDir": "/pagePark/cli"
}

connect ECONNREFUSED 127.0.0.1:1349

**Comment by sbwaters** [comment]
Restarted Ubuntu.

**Comment by scripting** [comment]
You didn't ask for this advice, but if you're really serious about running PagePark, you should get a book on running Linux and read it, and keep it around for reference. You shouldn't use this space for support on Linux. I usually won't answer questions on this topic, I hope you understand I have plenty of work to do and this is not fair -- I am not the support department for Linux. And I'm not about to take that job on.

**Comment by sbwaters** [comment]
CLI is a /scripting/pagePark tool, and, not part of Linux, would not have been documented there. 

I did not find CLI described in the ordinary pagePark docs or when I googled extensively about killing the pagePark process. I suggest adding it to the pagePark ReadMe. It seems a useful tool.

My fault. I did not recall installing it.
