### ISSUE TITLE
Breaking change in `mime` package

### ISSUE THREAD

**Issue by davisshaver** [scripting/pagePark#7]
`lookup()` renamed to `getType()`. https://www.npmjs.com/package/mime

Should we pin to v1.x or update? Glad to put a PR together. I've switched to `getType()` in it seems to work FWIW.

**Comment by scripting** [comment]
Thanks for the report. I just made the fix, it's in v0.7.6.

FWIW -- I don't buy this "breaking change" thing. I suppose there might possibly be times when you have to release a breaking change. But this seems gratuitous to me. 

Funny thing is that I have a perfectly good MIME translator function in daveutils, but I switched to use this package to be more Node-like. Oy.

**Comment by scripting** [comment]
Update: More trouble with the mime package. At random times, I'd get this error message in the log, after the server stopped running:

`Object #<Mime> has no method 'getType'`

It happened twice. I fixed it by reinstalling the app. The third time, I just replaced the package with the daveutils routine that does the same thing. One less dependency on a tiny package that believes in breaking changes.
